version: "3.9"

services:
  bot:
    build: .
    container_name: gpt_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QUOTE_TOKEN=${QUOTE_TOKEN}
      - GPT_URL=${GPT_URL}
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"


  db:
    image: postgres:15
    container_name: gpt_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: telegramDatabase
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: gpt_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: