CREATE TABLE gptmessages_test
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id  BIGINT,
    message VARCHAR(255),
    role    VARCHAR(255),
    CONSTRAINT pk_gptmessagestest PRIMARY KEY (id)
);