CREATE TABLE gptmessages_test
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id VARCHAR,
    message VARCHAR(255),
    role    VARCHAR(255),
    CONSTRAINT pk_gptmessages_test PRIMARY KEY (id)
);

ALTER TABLE gptmessages_test
    ADD CONSTRAINT FK_GPTMESSAGES_TEST_ON_CHAT FOREIGN KEY (chat_id) REFERENCES users (chat_id);